Dockerfile
docker-rebuild.sh
environment.sh

This introduces a Dockerfile and environment.sh to aid in setting up fresh systems/containers to test in.
The environment.sh will attempt to install all databases used in the test suite. It'll probably clobber existing ones, so you probably don't want to run it in an environment you care about.
Note that upon logging in, nothing is running. You can run `supervisord` to spin up all the services needed, or you can run individual components if you want.

Test environment

---

.gitignore
.travis.yml
lib/defaults.js
lib/probes/levelup.js
package.json
test/probes.levelup.js

This is basic instrumentation for the levelup module.
It includes experimental instrumentation for the batch command. It currently replaces KVKey with KVKeys and KVOps, which are simply arrays of strings. It can also be used as a [chainable API](https://github.com/rvagg/node-levelup#dbbatch-chained-form). The chainable mode doesn't currently work. Also, buffer values probably don't work either yet.
Does the KVKeys/KVOps approach seem reasonable?
You can also use read/write streams with levelup, which I haven't looked too deeply at yet. That looks like a more complicated thing and I'm not sure exactly how we'd want to represent it, or if we even *want* to instrument it.

[levelup] Instrumentation

---

lib/probes/http.js
test/probes.express.js

This fixes a bug where high volumes of requests could leak event listeners.

[http] Patch detachSocket to detect request termination

---

lib/require-patch.js

Factory function modules are not being loaded correctly on subsequent `require()` calls. This fixes that.

Make factory function modules work correctly with multiple requires

---

.travis.yml
deps.sh
lib/defaults.js
lib/probes/oracledb.js
package.json
test/probes/oracledb.test.js

Here's some basic instrumentation for the new, official Oracle DB driver. The module itself only builds on a few specific versions of node 0.10.x currently, so it's installed separately from other dev dependencies to allow TravisCI to ignore when it fails to install and just skip the tests for that node release.
Also, we'll need to figure out what to do about testing it on TravisCI, as they don't have Oracle support built-in. Like MSSQL, we'll need a separate testing database.

[oracle] Instrumentation

---

lib/probes/http.js

HTTP client requests need their own run scope so they don't step on each other.

[http] Prevent http(s) clients from crossing streams and awakening zalgo

---

test/probes/cassandra-driver/prepare.js
test/versions.js

Seems recent versions of cassandra-driver are a little less forgiving of params/options argument positions.

[cassandra-driver] Fix tests for recent module versions

---

lib/probes/mysql.js

This fixes `Object #<Object> has no method '_implyConnect'` errors.

[mysql] Fix wrong-context issue

---

bin/node-tv

This replaces the non-descriptive error when no file path is given to `node-tv` with a warning that more clearly describes the issue.

[node-tv] Add usage warning when path is not present

---

lib/index.js

This prevents an error when searching for module versions while the working directory is not the app root.

[misc] Fail gracefully when searching for node_modules folder

---

test/versions.js

Some module versions are buggy, or fail to install/build on newer node versions, so I've adjusted the support-matrix `versions.js` to reflect that.

[test] Exclude buggy module versions from support-matrix testing

---

test/error.test.js
test/probes/amqp.test.js
test/probes/cassandra-driver.test.js
test/probes/memcached.test.js
test/probes/mongodb.test.js
test/probes/mysql.test.js
test/probes/node-cassandra-cql.test.js
test/probes/pg.test.js
test/probes/redis.test.js
test/probes/redis/pubsub.js

This PR changes the tests to use docker link env variables for db hosts, where available. This makes testing in a network of docker containers easier.

[test] Use docker link env variables for db hosts, where available

---

lib/probes/tedious.js

This binds the connection emitter to the request context at creation time.

[tedious] Fix tedious support for io.js 2.x

---

test/probes/mongodb.test.js
test/versions.js

The tests were not compatible with the 2.x range of mongodb. This fixes that.

[test] Fix mongodb tests to work with 2.x

---

lib/probes/express.js

This prevents `TypeError - Cannot call method 'profile' of undefined`, which occurs when wrapping a route in a profile after the request context has been lost.

[express] Prevent route profiles throwing errors after lost context

---

test/helper.js

This makes it easier to generate test traces to send to the real tracelyzer. Just set `emitter.forward = true` and all messages passed through the mock tracelyzer will also get forwarded to the real tracelyzer.

[test] Add emitter setting to forward messages to real tracelyzer

---

lib/probes/mysql.js
test/probes/mysql.test.js

This prevents erroneous arguments failing within the instrumentation, and reports errors thrown by mysql itself as an info event.

[mysql] Report caller errors

---

lib/probes/hapi.js
package.json

As of hapi 8.5.0, the Request class is now constructed by calling `request` on a generator class instance.

[hapi] Support hapi 8.5.x+

---

test/probes/mysql.test.js

Prevent old mysql versions from testing object values, since they do not support that feature.

[mysql] Skip object value test on versions that don't support it

---

test/versions.js

This corrects the support matrix range for levelup so I don't get the failure on 0.16.0.

[test] Fix levelup support matrix range

---

test/probes/cassandra-driver.test.js
test/probes/node-cassandra-cql.test.js

This ensures the cassandra test keyspace exists before attempting to use it.

[test] Ensure cassandra test keyspace exists

---

lib/probes/memcached.js
test/probes/memcached.test.js

Memcached wasn't including the RemoteHost key/value pair, so I added it here.

[memcached] Ensure presence of RemoteHost k/v pair

---

lib/defaults.js
lib/probes/http.js
test/probes/http.test.js
test/probes/http/query-filtering.js
test/probes/https.test.js
test/probes/https/query-filtering.js

This adds support for filtering out URL query params when reporting http(s)-client layers. Server support is next.

[http] URL query filtering

---

lib/probes/cassandra-driver.js
lib/probes/fs.js
lib/probes/http.js
lib/probes/levelup.js
lib/probes/memcached.js
lib/probes/mongodb.js
lib/probes/mysql.js
lib/probes/node-cassandra-cql.js
lib/probes/oracledb.js
lib/probes/pg.js
lib/probes/redis.js
lib/probes/tedious.js

This adds spec keys to instrumentation for module types we have specs for. The template rendering spec is notably absent for now.

[misc] Add Spec keys to instrumentations that have defined specs

---

test/probes/hapi.test.js

Testing hapi against pre-8.x versions broke in another recent PR, this fixes them.

[test] Fix hapi tests for pre-8.x versions

---

lib/probes/co-render.js
lib/probes/koa-route.js
lib/probes/koa-router.js
test/probes/co-render.test.js
test/probes/koa-resource-router.test.js
test/probes/koa-route.test.js
test/probes/koa-router.test.js
test/probes/koa.js
test/versions.js

This cleans up the koa-related tests to work with node 4.x and splits them up to more easily isolate support-matrix testing.

[test] Split up koa tests and ensure they work across all versions

---

package.json

Memcached just updated with node 4.x support, so lets throw that in too.

[test] Update memcached test dependency

---

lib/probes/http.js
package.json
test/helper.js
test/probes/http.test.js
test/probes/http/client-object.js
test/probes/http/client.js
test/probes/http/query-filtering.js
test/probes/http/stream.js
test/probes/https.test.js
test/probes/https/client-object.js
test/probes/https/client.js
test/probes/https/query-filtering.js
test/probes/https/stream.js

This is an attempt to report http socket errors without interfering with the error event special-case machinery.

[error] Report socket errors without changing listener behaviour

---

lib/index.js
test/custom.test.js

This is a quick attempt at making the custom instrumentation API work when liboboe is not present.

[custom] Make custom instrumentation a no-op without liboboe

---

lib/probes/amqp.js
package.json
test/probes/amqp.test.js

This fixes an issue with some callbacks not being present when amqp is used via celery.

Fix amqp issue when used with celery

---

test/probes/hapi.bench.js

This updates the hapi benchmarks to work with hapi 9.x+.

[bench] Fix hapi benchmark for 9.x+

---

lib/defaults.js
lib/probes/mongodb-core.js
package.json
test/helper.js
test/probes/mongodb-core.test.js
test/probes/redis/pubsub.js
test/versions.js

This provides instrumentation for `mongodb-core`, which is the lower-level driver introduced to back the 2.x range of the `mongodb` module. By instrumenting the lower-level driver, we get support for some alternate mongodb modules, and better support for identifying queried hosts.

Mongodb core instrumentation

---

Vagrantfile

Mongo 2.4 is also needed in the local test environment.

[test] Add mongo 2.4 to vagrantfile

---

lib/probes/mongodb-core.js
test/probes/mongodb-core.test.js
test/probes/mongodb.test.js

The mongodb-core work was lacking 2.4 support. This addresses that and adds automated testing for it.

[mongodb-core] Add 2.4 support

---

lib/probes/mysql.js

MySQL connect function can be called without a callback.

[mysql] Support callback-less connect

---

lib/probes/mongodb.js

This prevents double reporting when the lower-level driver is also reporting.

[mongodb] Disable instrumentation for versions using mongodb-core

---

test/versions.js

This ensures support-matrix runs test director.

[test] Add director version range to support matrix config

---

test/probes/tedious.test.js

This prevents tedious tests from attempting to run while an MSSQL server is not available. The `TEST_SQLSERVER_EX` environment variable must be present to enable the tests.

[test] Disable tedious when address env var not present

---

Vagrantfile
docker-containers.json
docker.rb

The container details have now been moved to a shared json file at `docker-containers.json`, which can be used by both the `Vagrantfile` and `docker.rb` to spin up the necessary test containers.

[test] Support starting docker test services directly

---

lib/probes/http.js
test/probes/http.test.js
test/probes/https.test.js

This fixes an issue that caused the nodejs layer from http or https servers to never send the exit event, holding the liboboe event for it in memory indefinitely.

http: Fix httpServer.setTimeout(...) exit event leak

---

package.json

@Qard I just realized my PR had "array-flatten" in devDependencies instead of dependencies. :( Because of this 2.4.4 is broken. Should be an easy fix. Sorry about that.

move array-flatten to dependencies

---

lib/profile.js
test/profile.test.js

This includes the changes from #140, expanding the tests to verify the structural integrity of the trace.

Support info and error events within profiles

---

lib/event.js
lib/layer.js
test/error.test.js
test/helper.js
test/layer.test.js
test/probes/express.test.js

This fixes makes internal events chain properly, makes sub layers link correctly around internal events and expands the test suite around the behaviour of how internal events work and the custom instrumentation interfaces to create them manually.

layer, event, error: Fix internal event chaining

---

lib/probes/bcrypt.js
package.json
test/probes/bcrypt.test.js
test/versions.js

This adds support for propagating the CLS context through bcrypt.

bcrypt: Add patch to propagate CLS

---

lib/probes/generic-pool.js
package.json
test/probes/generic-pool.test.js
test/versions.js

This patches generic-pool, which provides the underlying pooling mechanism for many different modules and was previously causing CLS to lose context any time `pool.acquire(...)` was called while a connection was not immediately ready.

generic-pool: Patched to propagate CLS context

---

lib/probes/mongoose.js
package.json
test/probes/mongoose.test.js
test/probes/node-cassandra-cql.test.js
test/versions.js

This updates the mongoose patches to work up to the latest version of mongoose and adds some proper testing of the CLS context propagation.

mongoose, test: Update mongoose patches and test it better

---

test/probes/mysql.test.js
test/probes/pg.test.js

Semaphore CI requires the use of some different env variables to connect to mysql and postgres. This adds that to the tests.

test: Support semaphore CI environment vars

---

test/probes/pg.test.js
test/probes/raw-body.test.js

This prevents some intermittent test failures.

test: Minor fixes

---

lib/index.js
test/custom.test.js
test/helper.js

This adds support for starting a fresh trace or continuing a remote trace, with sampling applied.

custom: Add tv.startAndContinueTrace(...) and tv.traceId

---

lib/index.js
test/basics.test.js

The `tv.sample(...)` function was assigning directly to `tv.sampleRate`, which is the setter for specifying a manual sample rate. This is incorrect behaviour and has therefore been fixed.

core: Fix issue with sample data reassigning sample rate

---

test/probes/hapi.test.js
test/versions.js

Newer versions of hapi use ES6 features without transpilation, breaking old versions of node. These changes make old versions of node skip those tests.

test: Skip hapi tests when version expects ES6 features not present

---

lib/index.js
test/custom.test.js

This adds support for passing `X-TV-Meta` values into `tv.startOrContinueTrace(...)`.

custom, test: Support startOrContinueTrace with X-TV-Meta

---

lib/probes/amqp.js
test/probes/amqp.test.js

This adds pushq and job spec support to amqp, to track job processing.

amqp: Support pushq and job specs

---

lib/probes/raw-body.js
test/probes/raw-body.test.js

This fixes an issue with how co-body uses the newer promise support in raw-body.

raw-body: Support promise returns from 2.x

---

test/probes/fs.test.js

This fixes the fs.realpath test to compensate for the function being broken from node 6.0 to 6.3. See https://github.com/nodejs/node/pull/7899 for more details.

fs, test: Fix realpath test to compensate for node 6.0-6.3 being broken

---

test/probes/mysql.test.js

This test is no longer valid as mysql does not validate input values anymore. It just coerces them to valid, mostly nulls...

mysql, test: Remove no longer valid test

---

lib/probes/mongoose.js

The `args` input to `addQueue(...)` can now potentially be an `arguments` object, so it needs to be converted to an array.

mongoose: Ensure addQueue args is an array
