lib/defaults.js
lib/probes/tedious.js
package.json
test/probes.tedious.js

This includes instrumentation for [tedious](https://www.npmjs.org/package/tedious), the main mssql driver for node.

[mssql] Instrumentation

---

lib/index.js
lib/promise-patch.js

Add native promise support. This also makes request continuation through co/koa work.

Native promise support

---

package.json
test/probes/express.test.js
test/probes/hapi.test.js
test/probes/hello.tmpl
test/probes/rum.tmpl

This is dependent on the Koa branch, rebase and merge after that.

Use ejs templates in express and hapi tests

---

lib/defaults.js
lib/probes/raw-body.js
package.json
test/mocha.opts
test/probes/raw-body.test.js

This adds instrumentation for the body-parsing step of various frameworks.

[raw-body] Instrumentation

---

.travis.yml

[test] Add iojs + node 0.12 to .travis.yml, only npm update on node 0.8

---

bin/node-tv
package.json

This makes the node-tv binary a little more flexible.

[cli] Add flags for trace mode, sample rate and reporter host/port settings

---

.travis.yml
Gulpfile.js
lib/index.js
package.json
test/basics.test.js
test/helper.js
test/mocha.opts
test/probes/cassandra-driver.test.js
test/probes/express.test.js
test/probes/hapi.test.js
test/probes/http.test.js
test/probes/https.test.js
test/probes/koa.test.js
test/probes/levelup.test.js
test/probes/memcached.test.js
test/probes/mongodb.test.js
test/probes/mysql.test.js
test/probes/node-cassandra-cql.test.js
test/probes/oracledb.test.js
test/probes/pg.test.js
test/probes/raw-body.test.js
test/probes/redis.test.js
test/probes/restify.test.js
test/probes/tedious.test.js
test/versions.js
yuidoc.json

This is a little more verbose, but it'll allow me to speed up the watch testing by only running the test files relevant to the changed files.

Convert the task runner tools to gulpify

---

test/probes/tedious.test.js

The stored format of query parameters changed slightly in recent versions of tedious. This PR just checks for that.

[tedious] Fix tests for recent module versions

---

lib/probes/hapi.js
test/versions.js

This fixes `Uncaught error: No context available. ns.run() or ns.bind() must be called first.`

[hapi] Fix missing context issue

---

lib/defaults.js
lib/probes/amqp.js
package.json
test/helper.js
test/probes/amqp.test.js
test/probes/express.test.js
test/probes/hapi.test.js
test/probes/koa.js
test/probes/restify.test.js
test/versions.js

This is a quick spike on getting some amqp instrumentation.

[amqp] Instrumentation

---

.travis.yml
lib/defaults.js
lib/probes/amqp.js
package.json
test/helper.js
test/probes/amqp.test.js
test/probes/express.test.js
test/probes/hapi.test.js
test/probes/koa.js
test/probes/restify.test.js
test/versions.js

This fixes the failed merge from #64.

[amqp] Instrumentation *fixed*

---

lib/probes/mysql.js
test/probes/mysql.test.js
test/probes/mysql/object.js

This fixes an issue with using object values rather than arrays in mysql queries.

Fix mysql object values

---

lib/probes/hapi.js

I simplified how controller/action data is found for hapi. This also fixes a timing issue with io.js 2.x.

[hapi] Fix hapi support for io.js 2.x

---

Gulpfile.js
lib/layer.js
test/error.test.js

This adds the error spec data for errors originating from sync calls.

[errors] Add error spec data to sync errors

---

lib/defaults.js
lib/probes/fs.js
test/helper.js
test/probes/express.test.js
test/probes/fs.test.js
test/probes/hapi.test.js
test/probes/koa.test.js
test/probes/mongodb.test.js
test/probes/raw-body.test.js

This introduces fs tracing. I need to expand the test coverage, but everything works so far. :+1: 
We should also solidify a file system spec before I go much further.

[fs] Instrumentation

---

lib/defaults.js
lib/probes/zlib.js
package.json
test/probes/zlib.test.js

This adds zlib instrumentation. For key/value pairs, all it reports is the function name as "Operation".

[zlib] Instrumentation

---

test/probes/amqp.test.js

This is just a minor test fix to satisfy Jenkins.

[test] Fix amqp disconnect failures on 1.x

---

lib/probes/bluebird.js
package.json
test/probes/bluebird.test.js
test/versions.js

This fixes an issue with newer versions of bluebird that causes the internal domain to fail.

bluebird: Fix domain bind issue

---

test/probes/bluebird.test.js

Triggering the done callback within the requestStore context of the bluebird tests would cause the continuation to leak into subsequent tests. This fixes that.

[test] Trigger bluebird test completion indirectly to avoid accidental continuation

---

test/probes/pg.test.js

This ensures the test database is created, if not already present.

[test] Ensure postgres test db exists

---

test/probes/mysql.test.js

This ensure mysql creates the needed test database and table, if not already present.

[test] Ensure mysql test db exists

---

lib/defaults.js
lib/probes/crypto.js
test/probes/crypto.test.js

This is a first pass at crypto instrumentation. It currently reports update and digest/final/sign/verify calls separately, it might be better to do that differently. Needs further investigation.

[crypto] Instrumentation

---

lib/defaults.js
lib/probes/director.js
package.json
test/probes/director.test.js
test/versions.js

This adds support for the [director](https://www.npmjs.com/package/director) router, which backs the [flatiron](https://www.npmjs.com/package/flatiron) framework.

[director] Instrumentation

---

Vagrantfile

This just simplifies testing a bit by making a vagrant dev box with all the parts needed to run the full test suite.

[test] Add Vagrantfile for testing dev box

---

Gulpfile.js
package.json
test/basics.bench.js
test/custom.bench.js
test/error.bench.js
test/event.bench.js
test/layer.bench.js
test/probes/amqp.bench.js
test/probes/cassandra-driver.bench.js
test/probes/crypto.bench.js
test/probes/director.bench.js
test/probes/express.bench.js
test/probes/fs.bench.js
test/probes/hapi.bench.js
test/probes/http.bench.js
test/probes/koa.bench.js
test/probes/levelup.bench.js
test/probes/memcached.bench.js
test/probes/mongodb.bench.js
test/probes/mysql.bench.js
test/probes/node-cassandra-cql.bench.js
test/probes/oracledb.bench.js
test/probes/pg.bench.js
test/probes/redis.bench.js
test/probes/restify.bench.js
test/probes/tedious.bench.js
test/probes/zlib.bench.js
test/profile.bench.js

This is a WIP PR for expanding the test suite with some in-depth benchmarking of the core and various instrumentation components.

[bench] Started adding core benchmark tests

---

test/custom.test.js

Just expanding the tests a bit around liboboe absence.

[test] Expand custom instrumentation tests for when liboboe is not present

---

lib/probes/mongodb.js
test/helper.js
test/probes/mongodb.test.js
test/probes/mongodb/aggregation/map_reduce.js
test/versions.js

This fixes the incorrect RemoteHost value when using mongo replica sets in mongodb 1.x.

Fix mongo remotehost

---

test/helper.js
test/probes/amqp.test.js
test/probes/mongodb.test.js

This fixes an issue with the test helper eating errors when it shouldn't.

[test] Fix test helper

---

test/helper.js
test/probes/cassandra-driver.test.js
test/probes/node-cassandra-cql.test.js

Small improvement to cassandra tests

[test] Use address parser for cassandra tests

---

test/probes/cassandra-driver.test.js
test/probes/memcached.test.js
test/probes/mongodb.test.js
test/probes/mysql.test.js
test/probes/pg.test.js
test/probes/redis.test.js
test/probes/redis/pubsub.js
test/probes/tedious.test.js

This fixes a bunch of connection issues related to using the internal docker test services.

Fix docker test service hosts

---

test/probes/cassandra-driver.test.js
test/probes/redis/pubsub.js
test/versions.js

This just fixes some test failures from older versions of cassandra-driver and redis.

[test] Fix some minor test issues with older modules

---

test/probes/mongodb.test.js

This fixes up the 3.x support in the mongo tests.

[test] Make mongo tests support 3.x

---

lib/index.js

This adds a warning when a conflicting module is detected in the environment.

[misc] Warn when conflicting modules are detected in the environment

---

lib/index.js
lib/layer.js
test/custom.test.js
test/error.test.js
test/helper.js
test/layer.test.js
test/probes/cassandra-driver.test.js
test/probes/http.test.js
test/probes/https.test.js
test/probes/mysql.test.js
test/probes/node-cassandra-cql.test.js

This is the start of support for manually sending individual events. It is not complete yet.

[custom] Support manually sending error events

---

test/probes/redis/pubsub.js

Yay, moving connection details! >.>

[test] Fix redis pubsub test connection

---

Gulpfile.js

This is a rewrite of the gulp task runner to get coverage reporting working and to prevent the watcher task from being killed by test, coverage and bench tasks terminating the process.

[test] Rewrite the task runner so coverage and watch tests work properly

---

lib/probes/express.js
package.json
test/probes/express.test.js

This cleans up and fixes #136.

express: support arrays of middlewares

---

lib/probes/http.js
test/probes/http.test.js
test/probes/https.test.js

This fixes an issue with recent releases missing http status codes.

http, https: Fix missing status code

---

test/layer.test.js

The dangling info/error test has been failing randomly. These changes should help avoid that.

test: Make dangling info/error test more reliable

---

test/helper.js
test/probes/express.test.js

I updated the express tests to test some of the newer features in express.

test: Added a couple express tests

---

lib/probes/koa-resource-router.js
package.json
test/probes/fs.test.js

This fixes some minor things that were causing some tests to fail in node v6 rc3.

fs, koa-resource-router, test: Support node v6

---

.codeclimate.yml
README.md

Just adding some working badges.

misc: Add badges

---

lib/probes/koa-router.js

This PR does some quick sanity checks to see if the app object exists before running a filter method.

Fix exception in koa-router 5.4

---

CONTRIBUTING.md

This documents the dev process for working on the traceview agent.

misc: Add CONTRIBUTING.md

---

guides/instrumenting-a-module.md

This is a guide on how writing instrumentation for a module works.

doc: Add guide on how to instrument a module
